name : branch push workflow

on : 
  push : 
    branches : 
      - feature
jobs : 
  testing :
    runs-on : ubuntu-latest

    steps : 
      - name : Checkout Code
        uses : actions/checkout@v3

      - name : Say mahi
        run : |
          echo "Hello Mahendran"
  
