name: Run on Feature Branch

on:
  push:
    branches:
      - feature

jobs:
  run-feature-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print branch info
        run: echo "This job runs only when code is pushed to 'feature' branch"
